### PR TITLE
Compress all the .jpg images.

### PR DESCRIPTION
**Pull request by akbiggs**
The hazards-off versions of the images seemed to be significantly larger than
the hazards-on versions (about 7-8x larger on average). I think this was
because the hazards-off images weren't compressed.

I ran the following command to compress them:

mogrify -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB *.jpg

...based off of https://stackoverflow.com/a/44208640/176191

Now all the images seem to be around 10KBs.

I skimmed through the images and they seem fine, but happy for pushback if I missed something.

### CODE REVIEW

**Comment by agincel** [comment]
Hey, thanks a lot! I'll add you to a contributors section on the /about page!

**Comment by akbiggs** [comment]
Wow, thank you!

BTW, I'm forking Bans.Page to prototype an experimental stage selection ruleset for Ultimate. Is that okay with you? I give a link back to the original site in the prototype.

**Comment by agincel** [comment]
Sounds cool! If you could link us on your prototype that'd be great, and definitely shoot me a link when it's live so I can check it out!

**Comment by akbiggs** [comment]
For sure! Thanks!

**Comment by akbiggs** [comment]
If you're interested, you can check out a super early version of my fork at http://akbiggs.com/ssbu to get a sense of where I'm going. Source is at https://github.com/akbiggs/banspage.github.io/tree/save-ultimate (branch name is tongue-in-cheek).

Basically me and my brother are experimenting with a ruleset where the starter stages are chosen at random from a giant list of legal stages, and counterpicks are handled by having the loser select three stages from the entire list of legal stages and offering them to the winner of the previous game. Then starters and previous counterpicks are excluded from the counterpick list as you keep going into later games.

It seems like a bit of a crazy idea, but we're curious to experiment with it and see if it leads to more stage & character diversity in our local matches. We'll keep mucking around with the ruleset and formulating our thoughts around it.

**Pull request merged**
